### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by haithamkhedr**
Merge SlowFast/main into SlowFast-FSDP 

- Summary: Merge upstream to support MViTv2 models.
- Tests: Ran an experiment with config MVITv2_S_16x4. Training done with 30% top-1 val error.

### CODE REVIEW

**Comment by lyttonhao** [comment]
Looks good to me, overall! Thanks for the merging. I am wondering if you try some benchmark jobs for MViTv2 model to verify the merging works and performance is reasonable.

**Comment by haithamkhedr** [comment]
@lyttonhao I run MVITv2_S_16x4 config for 200 epochs and got 30 % top-1 val error.

**Comment by haithamkhedr** [comment]
> Looks good to me, overall! Thanks for the merging. I am wondering if you try some benchmark jobs for MViTv2 model to verify the merging works and performance is reasonable.


@lyttonhao I run MVITv2_S_16x4 config for 200 epochs and got 30 % top-1 val error.

**Comment by lyttonhao** [comment]
> > Looks good to me, overall! Thanks for the merging. I am wondering if you try some benchmark jobs for MViTv2 model to verify the merging works and performance is reasonable.
> 
> @lyttonhao I run MVITv2_S_16x4 config for 200 epochs and got 30 % top-1 val error.

Thanks! The results look good.

**Review by lyttonhao — APPROVED** [review]

**Pull request merged**
